# Generated by Django 3.1.6 on 2021-05-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер датчика')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Название датчика')),
                ('status', models.IntegerField(verbose_name='Статус датчика')),
            ],
        ),
        migrations.CreateModel(
            name='SensorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_sensor', models.IntegerField(verbose_name='Канал')),
                ('height_sensor', models.IntegerField(verbose_name='Высота')),
                ('type_sensor', models.CharField(max_length=100, verbose_name='Тип')),
                ('recorder_sensor', models.CharField(max_length=100, verbose_name='Регистратор')),
                ('discrete_frequency_sensor', models.IntegerField(verbose_name='Частота дискр.')),
                ('operator_sensor', models.CharField(max_length=100, verbose_name='Оператор')),
                ('perc_memr_free_storage', models.IntegerField(verbose_name='Процент свободной памяти')),
                ('perc_battery_storage', models.IntegerField(verbose_name='Процент аккамулятора')),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myServers.sensor')),
            ],
        ),
    ]
