# Generated by Django 3.1.6 on 2021-03-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер датчика')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Название датчика')),
                ('coordinates', models.IntegerField(unique=True, verbose_name='Кординаты')),
                ('time_zone', models.IntegerField(verbose_name='Часовой пояс датчика')),
                ('status', models.IntegerField(verbose_name='Статус датчика')),
                ('desc', models.TextField(max_length=400, verbose_name='Описание датчика')),
            ],
        ),
        migrations.CreateModel(
            name='SensorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_last_update', models.DateTimeField(verbose_name='Дата последнего обновления')),
                ('per_storage', models.IntegerField(verbose_name='Процент свободной памяти')),
                ('time_service', models.DateTimeField(verbose_name='Время последнего обслуживания')),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myServers.sensor')),
            ],
        ),
    ]
